name: Generate asciinema preview gif

# TODO: Before merging into benthayer/master, configure so this only runs on v* tags
on:
  push:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
    - name:  Generate fake preview.gif
      run: |
        mkdir -p /tmp/build/
        echo "Not a gif" > /tmp/build/preview.gif

    - name: Upload preview.gif
      uses: actions/upload-artifact@v2
      with:
        name: preview.gif
        path: /tmp/build/preview.gif

  create-pr:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    needs: generate
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Download artifacts
        uses: actions/download-artifact@v2
        with:
          name: preview.gif

      - name: Set tag
        id: vars
        run: |
          TAGNAME=$(git describe --tags)
          echo ::set-output name=tag::$TAGNAME

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          base: ascii-tagbranch
          commit-message: Automated update of preview.gif
          title: Updated preview.gif by create-pull-request@v3 action
          branch: create-pull-request/previewgif-${{ steps.vars.outputs.tag }}
